### ISSUE TITLE
V8 is damn fast, faster than C++ when it comes to numerics

### ISSUE THREAD

**Issue by zcbenz** [compilets/compilets#3]
So I just made it possible for compilets to compile TypeScript to native Node.js module. And I was thinking: well let's make a demo and show how JS could be made 10x faster.

```typescript
export function sieveOfEratosthenes(n: number): number[] {
  let primes = new Array<boolean>(n + 1).fill(true);
  primes[0] = false;
  primes[1] = false;
  for (let i = 2; i <= Math.sqrt(n); i++) {
    if (primes[i]) {
      for (let j = i * i; j <= n; j += i) {
        primes[j] = false;
      }
    }
  }
  let result: number[] = [];
  for (let i = 2; i <= n; i++) {
    if (primes[i]) {
      result.push(i);
    }
  }
  return result;
}
```

```c++
compilets::Array<double>* sieveOfEratosthenes(double n) {
  compilets::Array<bool>* primes = compilets::MakeObject<compilets::Array<bool>>(n + 1)->fill(true);
  primes->value()[0] = false;
  primes->value()[1] = false;
  for (double i = 2; i <= compilets::Math::sqrt(n); i++) {
    if (primes->value()[static_cast<size_t>(i)]) {
      for (double j = i * i; j <= n; j += i) {
        primes->value()[static_cast<size_t>(j)] = false;
      }
    }
  }
  compilets::Array<double>* result = compilets::MakeArray<double>({});
  for (double i = 2; i <= n; i++) {
    if (primes->value()[static_cast<size_t>(i)]) {
      result->push(i);
    }
  }
  return result;
}
```

The demo was a simple prime number generator using sieve of eratosthenes.

```console
$ ./benchmark.js
sieveOfEratosthenes in JS: 18.446ms
sieveOfEratosthenes in C++: 15.246ms
```

Ehh C++ was only 16% faster, something must went wrong.

Profiling shows converting C++ vector to JS array took 50% of the time, and memory allocation took 10%.

Understandable overhead for returning an array of 78498 elements.

Let's change to a demo only involving numbers.

```typescript
export function isPrimeNumber(n: number): boolean {
  if (n <= 1) {
    return false;
  }
  for (let i = 2; i * i <= n; i++) {
    if (n % i === 0) {
      return false;
    }
  }
  return true;
}
```

```c++
bool isPrimeNumber(double n) {
  if (n <= 1) {
    return false;
  }
  for (double i = 2; i * i <= n; i++) {
    if (compilets::Mod(n, i) == 0) {
      return false;
    }
  }
  return true;
}
```

The new demo is a dumb function computing whether a number is prime.

```console
$ ./benchmark.js
isPrimeNumber in JS: 587.586ms
isPrimeNumber in C++: 3.998s
```

What? No I didn't put things in wrong order, and optimization is -O2.

The optimized C++ code indeed took 6.8x more time.

A simple way to improve the C++ code is to change `double` to `int64_t`, I manually changed the converted code and ran benchmark again.

```console
$ ./benchmark.js
isPrimeNumber in JS: 587.178ms
isPrimeNumber in C++: 647.104ms
```

Much faster, but still slower than V8!

There are 2 conclusions:

* V8 apparently can find out the number is integer in the function and use integral instructions.
* For numeric computations V8's JIT is faster than compiled and optimized C++ code.

You can try it yourself with https://github.com/compilets/quick-start.

**Comment by deepak1556** [comment]
Hi @zcbenz 👋 

I got curious of this post and tried the quick-start on my m1 machine. The following are the numbers I get with Node.js v22.8.0,

```
% ./bechmark.js 
sieveOfEratosthenes in JS: 23.091ms
sieveOfEratosthenes in C++: 16.518ms
isPrimeNumber in JS: 4.003s
isPrimeNumber in C++: 3.847s
```

Wondering if the numbers you got are from newer runtime version ?

> Though I'm not familiar with V8's JIT to verify them.

You can get the generated assembly code from V8 using `--print-opt-code` and compare it with the instructions generated for the shared library.

**Comment by deepak1556** [comment]
Additionally on the c++ benchmark, in the current measurement it includes the time for crossing the V8 -> C++ boundary over the bindings which would include type checks. Should the benchmark maybe changed to only measure the time inside `isPrimeNumber` ?

**Comment by zcbenz** [comment]
> I got curious of this post and tried the quick-start on my m1 machine. The following are the numbers I get with Node.js v22.8.0,

I was testing on x64 mac, and I get similar results with yours on m3 mac:

```
$ ./bechmark.js 
sieveOfEratosthenes in JS: 21.498ms
sieveOfEratosthenes in C++: 12.328ms
isPrimeNumber in JS: 2.886s
isPrimeNumber in C++: 2.764s
```

Not sure if it is a bug of V8 or a feature of x64 processors.

> Should the benchmark maybe changed to only measure the time inside `isPrimeNumber` ?

The overhead of JS-native boundary is quite low, if you remove the function body the remaining time is the overhead of function call.

```
isPrimeNumber in JS: 0.02ms
isPrimeNumber in C++: 0.004ms
```

**Comment by DavidJCobb** [comment]
> The optimized C++ code indeed took 6.8x more time.
> 
> A simple way to improve the C++ code is to change double to `int64_t`

What optimized code? Why are you calling `compilets::Mod(n, i)` and not just doing `n % i`? [`compilets::Mod` returns a `double` even if the parameters are integers](https://github.com/compilets/compilets/blob/71fda9ec7ce0816c82b28451d532ab9b8e66d5ac/cpp/runtime/math.h#L58), so you still take a perf hit from needing to cast back and forth. A compiler *might* strip that cast out, but I wouldn't bet on it.

It's worth noting that [V8 will store integer arrays as integers, not doubles, whenever it believes it can](https://v8.dev/blog/elements-kinds); so your JS code was already using `int32_t` under the hood to some degree. Your comparison to C++ using doubles (for a test that non-numbers could never pass!) is invalid.

Your sieve of Erastosthenes code is bad in both languages, too: the `primes` array is pointless. If you find a prime, just push it into `result` then and there! Don't allocate an entire array of bools that you're just going to throw away! Don't do an entire second loop just to translate those bools to something you could've constructed in the desired format to begin with!
